/*
 * This Kotlin source file was generated by the Gradle 'init' task.
 */
package KotlinDSA

import KotlinDSA.linkedList.LinkedList

class App {
    val greeting: String
        get() {
            return "Hello World!"
        }
}

fun main() {
    val list = LinkedList<String>()
    list.push("meatball").append("turkey").append("ham").append("bacon")
    println(list.toString())



}
