/*
 * This Kotlin source file was generated by the Gradle 'init' task.
 */
package KotlinDSA

import KotlinDSA.leetcode.TwoSum
import KotlinDSA.linkedList.LinkedList

class App {
    val greeting: String
        get() {
            return "Hello World!"
        }
}

fun main() {
   TwoSum.twoSumMethod(intArrayOf(10, 20, 30, 40, 50),50)




}
